import React from "react";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import type { ReportData } from "./reportData.js";

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 10, fontFamily: "Helvetica" },
  pageLandscape: { padding: 32, fontSize: 10, fontFamily: "Helvetica" },
  title: { fontSize: 18, marginBottom: 4, fontFamily: "Helvetica-Bold" },
  subtitle: { fontSize: 10, color: "#555555", marginBottom: 16 },
  sectionTitle: { fontSize: 13, fontFamily: "Helvetica-Bold", marginTop: 16, marginBottom: 6 },
  summaryRow: { flexDirection: "row", marginBottom: 3 },
  summaryLabel: { width: 160, color: "#555555" },
  tableHeader: { flexDirection: "row", borderBottom: 1, borderBottomColor: "#000000", paddingBottom: 4, marginBottom: 4 },
  tableRow: { flexDirection: "row", paddingVertical: 3, borderBottom: 0.5, borderBottomColor: "#dddddd" },
  colAddress: { width: "34%", overflow: "hidden", paddingRight: 4 },
  colDepth: { width: "10%", overflow: "hidden", paddingRight: 4 },
  colFlags: { width: "56%", overflow: "hidden" },
  colTxAddress: { width: "30%", overflow: "hidden", paddingRight: 4, fontSize: 8 },
  colTxAmount: { width: "18%", overflow: "hidden", paddingRight: 4 },
  colTxTime: { width: "22%", overflow: "hidden" },
  flagText: { color: "#b91c1c" },
  footer: { position: "absolute", bottom: 20, left: 32, right: 32, fontSize: 8, color: "#888888", textAlign: "center" },
});

export async function generateReportPdf(report: ReportData): Promise<Buffer> {
  const doc = React.createElement(
    Document,
    {},
    // Page 1: Summary + Wallets (portrait)
    React.createElement(
      Page,
      { size: "A4", style: styles.page },
      React.createElement(Text, { style: styles.title }, "CFTA Trace Report"),
      React.createElement(
        Text,
        { style: styles.subtitle },
        `Generated ${report.generatedAtIso}  |  Start wallet: ${report.startAddress}`
      ),
      React.createElement(Text, { style: styles.sectionTitle }, "Summary"),
      React.createElement(
        View,
        {},
        summaryRow("Wallets traced", String(report.summary.totalWallets)),
        summaryRow("Transfers traced", String(report.summary.totalTransfers)),
        summaryRow("Trace depth limit reached", report.summary.truncated ? "Yes" : "No"),
        summaryRow("Total flags", String(report.summary.flagCount)),
        summaryRow("Cross-case matches", String(report.summary.crossCaseCount)),
        summaryRow("Known exchange wallets", String(report.summary.exchangeCount))
      ),
      React.createElement(Text, { style: styles.sectionTitle }, "Wallets"),
      React.createElement(
        View,
        { style: styles.tableHeader },
        React.createElement(Text, { style: styles.colAddress }, "Address"),
        React.createElement(Text, { style: styles.colDepth }, "Hop"),
        React.createElement(Text, { style: styles.colFlags }, "Flags")
      ),
      ...report.wallets.map((w) =>
        React.createElement(
          View,
          { style: styles.tableRow, key: w.address },
          React.createElement(Text, { style: styles.colAddress }, `${w.address}${w.isStartNode ? " (start)" : ""}`),
          React.createElement(Text, { style: styles.colDepth }, String(w.depth)),
          React.createElement(
            Text,
            { style: [styles.colFlags, w.flagReasons.length > 0 ? styles.flagText : {}] },
            w.flagReasons.length > 0 ? w.flagReasons.join("; ") : "—"
          )
        )
      ),
      React.createElement(
        Text,
        { style: styles.footer, fixed: true },
        "Generated by CFTA — Crypto Flow & Fraud Analytics. For internal investigative use."
      )
    ),
    // Page 2: Transfers (landscape for wider columns)
    React.createElement(
      Page,
      { size: "A4", orientation: "landscape", style: styles.pageLandscape },
      React.createElement(Text, { style: styles.sectionTitle }, "Transfers"),
      React.createElement(
        View,
        { style: styles.tableHeader },
        React.createElement(Text, { style: styles.colTxAddress }, "From"),
        React.createElement(Text, { style: styles.colTxAddress }, "To"),
        React.createElement(Text, { style: styles.colTxAmount }, "Amount"),
        React.createElement(Text, { style: styles.colTxTime }, "Timestamp")
      ),
      ...report.transfers.map((t) =>
        React.createElement(
          View,
          { style: styles.tableRow, key: t.transactionId },
          React.createElement(Text, { style: styles.colTxAddress }, t.source),
          React.createElement(Text, { style: styles.colTxAddress }, t.target),
          React.createElement(Text, { style: styles.colTxAmount }, `${t.amount} ${t.tokenSymbol}`),
          React.createElement(Text, { style: styles.colTxTime }, t.timestampIso)
        )
      ),
      React.createElement(
        Text,
        { style: styles.footer, fixed: true },
        "Generated by CFTA — Crypto Flow & Fraud Analytics. For internal investigative use."
      )
    )
  );

  return renderToBuffer(doc);
}

function summaryRow(label: string, value: string) {
  return React.createElement(
    View,
    { style: styles.summaryRow, key: label },
    React.createElement(Text, { style: styles.summaryLabel }, label),
    React.createElement(Text, {}, value)
  );
}